name: my_booking_application
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.9.2
  get: ^4.7.3
  get_storage: ^2.1.1
  intl: ^0.20.2
  image_picker: ^1.2.2
  socket_io_client: ^3.0.0
  firebase_core: ^4.9.0
  firebase_messaging: ^16.2.2
  flutter_local_notifications: ^21.0.0
  logger: ^2.7.0
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  google_sign_in: ^7.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  package_rename: ^1.10.1

flutter:

  uses-material-design: true

  assets:
    - assets/animation_files/
    - assets/images/
    - assets/icons/

  fonts:
    - family: arimo
      fonts: 
        - asset: assets/fonts/arimo/Arimo-Regular.ttf
          weight: 400
        - asset: assets/fonts/arimo/Arimo-Bold.ttf
          weight: 700
        - asset: assets/fonts/arimo/Arimo-Medium.ttf
          weight: 500  
        - asset: assets/fonts/arimo/Arimo-SemiBold.ttf
          weight: 600  
        - asset: assets/fonts/arimo/Arimo-Medium.ttf
          weight: 100    
    - family: roboto_slab
      fonts:
        - asset: assets/fonts/roboto_slab/RobotoSlab-Regular.ttf
          weight: 400
        - asset: assets/fonts/roboto_slab/RobotoSlab-Bold.ttf
          weight: 700
        - asset: assets/fonts/roboto_slab/RobotoSlab-Medium.ttf
          weight: 500  
        - asset: assets/fonts/roboto_slab/RobotoSlab-SemiBold.ttf
          weight: 600  
        - asset: assets/fonts/roboto_slab/RobotoSlab-Light.ttf
          weight: 100      

flutter_launcher_icons:
  android: true
  iOS: true
  image_path: "assets/icons/application_logo.png"

package_rename_config:
  android:
    app_name: "My Bookings"
    package_name: "com.allysoftsolutions.mybookings"


