// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2jKRrlmvFtW3WPgb2QdigGXRXi2F74BM',
    appId: '1:175183335539:web:e311efe179b46e72b09a06',
    messagingSenderId: '175183335539',
    projectId: 'mybookings-cdcf5',
    authDomain: 'mybookings-cdcf5.firebaseapp.com',
    storageBucket: 'mybookings-cdcf5.firebasestorage.app',
    measurementId: 'G-6S8QRF0WNP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFNeeA6CE0iTLG4JBTsY1Px3oirB7t2aQ',
    appId: '1:175183335539:android:d69a11c508200c3cb09a06',
    messagingSenderId: '175183335539',
    projectId: 'mybookings-cdcf5',
    storageBucket: 'mybookings-cdcf5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3IsiRafjCO3UFH6OMrJAQdlBB9bS0UhI',
    appId: '1:175183335539:ios:b6a3ca618c649fc7b09a06',
    messagingSenderId: '175183335539',
    projectId: 'mybookings-cdcf5',
    storageBucket: 'mybookings-cdcf5.firebasestorage.app',
    iosBundleId: 'com.example.myBookingApplication',
  );
}
